---

#
# [ install tomcat7 ]
#
# install tomcat7 for aws {{{

- name: ensure tomcat7 for aws is present
  yum:  name={{ item }} state=present
  with_items:
    - tomcat7
    - tomcat7-admin-webapps
    - tomcat7-docs-webapp
    - tomcat7-el-2.2-api
    - tomcat7-javadoc
    - tomcat7-jsp-2.2-api
    - tomcat7-lib
    - tomcat7-servlet-3.0-api
    - tomcat7-webapps
    - apache-tomcat-apis
  when: platform in ['aws']

# }}}
# install tomcat7 {{{

- name: ensure tomcat7 is present
  yum:  name={{ item }} enablerepo=jpackage state=present
  with_items:
    - tomcat7
    - tomcat7-admin-webapps
    - tomcat7-docs-webapp
    - tomcat7-el-2.2-api
    - tomcat7-javadoc
    - tomcat7-jsp-2.2-api
    - tomcat7-lib
    - tomcat7-servlet-3.0-api
    - tomcat7-webapps
    - apache-tomcat-apis
  when: platform not in ['aws']

# }}}

#
# [ place configuration for tomcat7 ]
#
# copy /etc/rc.d/init.d/tomcat7 {{{

#- name: copy /etc/rc.d/init.d/tomcat7
#  copy: src=etc/rc.d/init.d/tomcat7
#        dest=/etc/rc.d/init.d/tomcat7
#        owner=root group=root mode=0755

# }}}
# copy /etc/sysconfig/tomcat7 {{{

#- name: copy /etc/sysconfig/tomcat7
#  copy: src=etc/sysconfig/tomcat7
#        dest=/etc/sysconfig/tomcat7
#        owner=root group=root mode=0644

# }}}
# copy /etc/tomcat7/server.xml {{{

#- name: copy /etc/tomcat7/server.xml
#  copy: src=etc/tomcat7/server.xml
#        dest=/etc/tomcat7/server.xml
#        owner=root group=root mode=0644

# }}}
# copy /etc/tomcat7/tomcat7.conf {{{

#- name: copy /etc/tomcat7/tomcat7.conf
#  copy: src=etc/tomcat7/tomcat7.conf
#        dest=/etc/tomcat7/tomcat7.conf
#        owner=root group=root mode=0644

# }}}

