---

#
# [ place configuration for nginx ]
#
# copy /etc/nginx/conf.d/default.conf {{{

- name: copy /etc/nginx/conf.d/default.conf
  copy: src=nginx/conf.d/default.conf
        dest=/etc/nginx/conf.d/default.conf
        owner=root group=root mode=0644

# }}}

#
# [ call functions ]
#
# restart munin-nginx {{{

- name: restart munin-nginx
  raw:  |
        sleep 30 ;
        sudo service munin-fcgi-graph restart ;
        sudo service munin-fcgi-html  restart ;

  ignore_errors: yes

# }}}
# reload nginx {{{

- name:    reload nginx
  service: name=nginx enabled=yes state=reloaded

# }}}

