#!/bin/bash
#
# /etc/rc.d/init.d/asgard
#
# Starts the Asgard server
#
# chkconfig: 345 60 40
# description: Run Asgard server
# processname: java

# Source function library
. /etc/rc.d/init.d/functions

# Default values
ASGARD_HOME=/var/lib/asgard
ASGARD_JAR_FILE=/usr/share/asgard/lib/asgard.jar

# Check for existence of needed config file and read it
#ASGARD_CONFIG=/etc/sysconfig/asgard
ASGARD_CONFIG=/etc/asgard.conf

# Pull in cq settings
[ -f $ASGARD_CONFIG ] && . $ASGARD_CONFIG
ASGARD_USER=${ASGARD_USER:-"root"}

# Location of the log and PID file
LOG_FILE=/var/log/asgard/run.log
PID_FILE=/var/run/asgard.pid

# For SELinux we need to use 'runuser' not 'su'
SU="/bin/su -s /bin/sh"
test -x "/sbin/runuser" && SU="/sbin/runuser -s /bin/sh"

# Set ulimit
ulimit -n 65536

# Default return value
RETVAL=0


start() {
	echo -n $"Starting Asgard server: "

	# check if Asgard is already running
	test -f $PID_FILE && test -d /proc/$(cat $PID_FILE) && echo " Asgard is already running (pid  $(cat $PID_FILE))" && return $?

	# Run the Java process
	#ASGARD_HOME="$ASGARD_HOME" java $ASGARD_JVM_OPTS -jar $ASGARD_JAR_FILE >>$LOG_FILE 2>&1 &
	$SU - $ASGARD_USER -c "ASGARD_HOME=$ASGARD_HOME java $ASGARD_JVM_OPTS -jar $ASGARD_JAR_FILE" >>$LOG_FILE 2>&1 &
	RETVAL=$?

	# Wait till Java master process comes up
	sleep 1

	# Store PID of the Java master process into a file
	#echo $! > $PID_FILE
	echo $(pgrep -P $!) > $PID_FILE && kill -KILL $! 2>/dev/null

	if [ $RETVAL -eq 0 ] ; then
		success "Asgard startup"
	else
		failure "Asgard startup"
	fi

	echo
	return $RETVAL
}


stop() {
	echo -n $"Stopping Asgard server: "

	# Run the Java process
	kill $(cat $PID_FILE 2>/dev/null) >>$LOG_FILE 2>&1
	RETVAL=$?

	if [ $RETVAL -eq 0 ] ; then
		rm -f $PID_FILE
		success "Asgard stopping"
	else
		failure "Asgard stopping"
	fi

	if [ ! "$(cat $PID_FILE 2>/dev/null)" ] ; then
		rm -f $PID_FILE 2>/dev/null
	fi

	echo
	return $RETVAL
}


restart() {
	stop
	start
}


case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	restart
	;;
status)
	status -p $PID_FILE java
	RETVAL=$?
	;;
*)
	echo $"Usage: $0 [start|stop|restart|status]"
	RETVAL=2
esac


exit $RETVAL
