---

- hosts: self
  gather_facts: False
  sudo:  True
  connection: local

  tasks:
    # restart munin-fcgi-graph {{{

    - name:    restart munin-fcgi-graph
      service: name=munin-fcgi-graph enabled=yes state=restarted

    # }}}
    # restart munin-fcgi-html {{{

    - name:    restart munin-fcgi-html
      service: name=munin-fcgi-html enabled=yes state=restarted

    # }}}

