---

#
# [ place configuration for nginx ]
#
# copy /etc/nginx/conf.d/default.conf {{{

- name: copy /etc/nginx/conf.d/default.conf
  copy: src=nginx/conf.d/default.conf
        dest=/etc/nginx/conf.d/default.conf
        owner=root group=root mode=0644

# }}}

#
# [ call functions ]
#
# restart elasticsearch {{{

- name:    restart elasticsearch
  service: name=elasticsearch enabled=yes state=restarted

# }}}
# restart nginx {{{

- name:    restart nginx
  service: name=nginx enabled=yes state=restarted

# }}}

