---

#
# [ build firewall ]
#
# mkdir /root/bin {{{

- name: mkdir /root/bin
  file: path=/root/bin
        owner=root group=root mode=0755 state=directory

# }}}
# copy /root/buildfirewall.sh {{{

- name: copy /root/bin/buildfirewall.sh
  copy: src=root/bin/buildfirewall.sh
        dest=/root/bin/buildfirewall.sh
        owner=root group=root mode=0700

# }}}
# edit sshd_config and build firewall {{{

- name: build firewall
  raw:  >
    /root/bin/buildfirewall.sh ;

  ignore_errors: yes

# }}}

#
# [ place /etc/motd ]
#
# copy /etc/motd {{{

- name: copy /etc/motd
  copy: src=motd
        dest=/etc/motd
        owner=root group=root mode=0644

# }}}

#
# [ place configuration for nginx ]
#
# copy /etc/nginx/conf.d/default.conf {{{

- name: copy /etc/nginx/conf.d/default.conf
  copy: src=nginx/conf.d/default.conf
        dest=/etc/nginx/conf.d/default.conf
        owner=root group=root mode=0644

# }}}

#
# [ call functions ]
#
# restart elasticsearch {{{

- name:    restart elasticsearch
  service: name=elasticsearch enabled=yes state=restarted

# }}}
# restart nginx {{{

- name:    restart nginx
  service: name=nginx enabled=yes state=restarted

# }}}

