---

#
# [ update base packages ]
#
# yum update package database {{{

- name:    yum check-update
  command: yum check-update
  ignore_errors: yes

# }}}
# yum update {{{

- name:    yum update
  command: yum -y update

# }}}

#
# [ install packages ]
#
# install packages {{{

- name: ensure packages are present
  yum:  name={{ item }} enablerepo=epel state=present
  with_items:
    - bash-completion
    - bzip2
    - git
    - glances
    - htop
    - ncurses
    - ncurses-devel
    - openssl
    - openssl-devel
    - readline
    - readline-devel
    - rsync
    - tree
    - unzip
    - vim
    - w3m
    - wget
    - yum-plugin-fastestmirror
    - yum-plugin-priorities
    - zip
    - zlib
    - zlib-devel

# }}}

#
# [ build firewall ]
#
# copy /root/buildfirewall.sh {{{

- name: copy /root/buildfirewall.sh
  copy: src=root/buildfirewall.sh
        dest=/root/buildfirewall.sh
        owner=root group=root mode=0700

# }}}
# copy /root/edit_sshd_config.sh {{{

- name: copy /root/edit_sshd_config.sh
  copy: src=root/edit_sshd_config.sh
        dest=/root/edit_sshd_config.sh
        owner=root group=root mode=0700

# }}}
# edit sshd_config and build firewall {{{

- name: edit sshd_config and build firewall
  raw:  >
    /root/edit_sshd_config.sh ;
    /etc/rc.d/init.d/sshd restart ;
    /root/buildfirewall.sh ;

  ignore_errors: yes

# }}}

